webtalk_init -webtalk_dir F:\\Programdata\\CNNPR\\fpga\\fpga.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期五 四月 5 17:07:08 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "96cerghhlhjoj7jtvddfs4f4aq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1554455169046" -context "sdk\\\\bsp/1554455169046"
webtalk_add_data -client sdk -key hwid -value "1553655758529" -context "sdk\\\\bsp/1554455169046"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1554455169046"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1554455169046"
webtalk_add_data -client sdk -key uid -value "1554455170836" -context "sdk\\\\application/1554455170836"
webtalk_add_data -client sdk -key hwid -value "1553655758529" -context "sdk\\\\application/1554455170836"
webtalk_add_data -client sdk -key bspid -value "1554455169046" -context "sdk\\\\application/1554455170836"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1554455170836"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1554455170836"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1554455170836"
webtalk_transmit -clientid 348230503 -regid "" -xml F:\\Programdata\\CNNPR\\fpga\\fpga.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\Programdata\\CNNPR\\fpga\\fpga.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\Programdata\\CNNPR\\fpga\\fpga.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
